# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DiaryApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DiaryApp
 	pod 'RxSwift', '~> 4.3.1'
        pod 'RxCocoa', '~> 4.3.1'
	pod 'Alamofire', '~> 5.2'

end
